
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ttfvexjtlirejwegvnpx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0ZnZleGp0bGlyZWp3ZWd2bnB4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMDUzOTcsImV4cCI6MjA2NTg4MTM5N30.MXyzT-3JOBV3dl-drdl3tirL-v0q1sZwx0iKN3Un1Vg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Test connection and log configuration
console.log('Supabase client initialized');
console.log('URL:', SUPABASE_URL);
console.log('Auth storage configured for localStorage');

// Test authentication state
supabase.auth.getSession().then(({ data: { session }, error }) => {
  if (error) {
    console.error('Error getting session:', error);
  } else {
    console.log('Current session:', session?.user?.email || 'No user logged in');
  }
});
